### PR TITLE
Don't use key.json

### PR DESCRIPTION
**Pull request by lizlooney**
Added key.json to .gcloudignore.
Modified model_trainer.__get_ml_service so it doesn't use key.json.
Modified util.storage_client so it doesn't use key.json.

### CODE REVIEW

**Comment by cmacfarl** [comment]
I support this change in general, but this does break local instances of the flask server, which I've found quite useful.  Can we have an option to pull a service account key file from the local directory if, say, an environment variable is set?  See [this change](https://github.com/FIRST-Tech-Challenge/fmltc/pull/78/files#diff-79e5a81d83111f3928e56c4c70c7cc1a2aaadb5edfdc87efce9aa066b89229b2) for an example of how I'm using environment variables to set up constants.py.

**Comment by lizlooney** [comment]
Sure, do you want me to merge this now and then you can add the environment variable stuff?

**Comment by cmacfarl** [comment]
I'd prefer an option that doesn't break the local workflow before this is merged.

**Comment by lizlooney** [comment]
> I'd prefer an option that doesn't break the local workflow before this is merged.

Sure, that makes sense. I'll update this after the terraform branch is merged into main.

**Comment by lizlooney** [comment]
With this PR, I can't upload a video.

**Pull request closed without merging**
