### PR TITLE
Don't call OpenIdConnect if we aren't using OIDC.

### PR DESCRIPTION
**Pull request by cmacfarl**

### CODE REVIEW

**Comment by lizlooney** [comment]
Did you test this? When I tried this, I got an error on line 150 ```@oidc.require_login``` about oidc not being assigned.

**Comment by cmacfarl** [comment]
That decorator should only be called if USE_OIDC is set.  I'll take a closer look, but in the meantime do you have a stack trace to go along with that error?

**Comment by lizlooney** [comment]
When the python file is loaded (which happens when you deploy the cloud function and when the app engine server starts up, the annotation function is called and it returns a wrapper. When the login_via_oidc function is called later, it calls the wrapper.

**Comment by lizlooney** [comment]
With this I get:
Traceback (most recent call last): File "/layers/google.python.pip/pip/bin/functions-framework", line 8, in <module> sys.exit(_cli()) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1137, in __call__ return self.main(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1062, in main rv = self.invoke(ctx) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 763, in invoke return __callback(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/_cli.py", line 37, in _cli app = create_app(target, source, signature_type) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 237, in create_app spec.loader.exec_module(source_module) File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/workspace/main.py", line 79, in <module> oidc = OpenIDConnect(app) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask_oidc/__init__.py", line 124, in __init__ self.init_app(app) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask_oidc/__init__.py", line 133, in init_app secrets = self.load_secrets(app) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask_oidc/__init__.py", line 192, in load_secrets return _json_loads(open(app.config['OIDC_CLIENT_SECRETS'], FileNotFoundError: [Errno 2] No such file or directory: 'client_secrets.json'

**Comment by cmacfarl** [comment]
@lizlooney 8fe21bf looks good to me.

**Pull request merged**
