### PR TITLE
Several improvements to the label video page.

### PR DESCRIPTION
**Pull request by lizlooney**
Fixed issue 160 Ghosting With Bounding Boxes

Fixed issue 161 Differentiating Bounding Boxes
Differentitate bounding boxes by using different colors.
Show label above the bounding box.

Fixed issue 162 Bounding Box Deselects When Cursor Goes Off Screen
Cursor may go out of the window while creating or resizing a bounding box.

Fixed issue 180 Able to Create Invalid Bounding Box
Don't let user make invalid boxes.
Correct invalid boxes created by tracker.

Fixed issue 181 Problem with counting unlabeled and labeled frames
Don't save a box if it doesn't have a label.

Added code to show vertical and horizontal lines as the mouse moves above the image.

### CODE REVIEW

**Comment by uvidyadharan** [comment]
**Fixed issue 160 Ghosting With Bounding Boxes:**
- Works great

**Fixed issue 161 Differentiating Bounding Boxes**:
- Works well generally
- Has trouble dealing with long labels (lack of limit on labels though that is not necessarily supposed to be addressed by this PR) 
  - Can go offscreen especially when close to edges
image
 - Overlapping labels  are a bit wonky
image

 - Minor but consider rounding the edges label boxes on image

**Fixed issue 162 Bounding Box Deselects When Cursor Goes Off Screen**
- For normal use case works great
- Possibly has bug in which a new bounding box is created when coming back onto the screen. It only happens in certain cases but may be my mouse having issues.
- If the mouse is moved too fast off the screen it will leave the corner not at the edge of the screen but a but before. As you move the mouse slower it gets closer to the screen. This is perhaps something to do with the refresh rate. 

https://user-images.githubusercontent.com/55924756/141238786-3181affd-c13d-4b26-882d-64b027f762f9.mp4 

**Fixed issue 180 Able to Create Invalid Bounding Box**
- Works perfectly 

**Fixed issue 181 Problem with counting unlabeled and labeled frames**
- Works well for the most part
- Was able to find bug where negative unlabeled frames were found. Still working on replication. 
image

**Added code to show vertical and horizontal lines as the mouse moves above the image.**
- What purpose do the lines serve?

**Comment by lizlooney** [comment]
> What purpose do the lines serve?

Someone (maybe Danny) saw them [here](https://youtu.be/L6_h4hj99PQ?t=120) and asked if I could add them.

**Comment by lizlooney** [comment]
> Minor but consider rounding the edges label boxes on image

I've changed the code to use beveled corners (instead of rounded) on the bounding box. Because it gets scaled down, sometimes the rounded corners disappear and look like normal corners. When beveled corners are scaled down, they look round.

I've also updated the rectangle round the label text to have beveled corners (which look rounded).

**Comment by lizlooney** [comment]
> If the mouse is moved too fast off the screen it will leave the corner not at the edge of the screen but a bit before.

I've fixed that.

**Comment by uvidyadharan** [comment]
The new chamfered edges work perfectly. However I have found a new problem at low resolutions. The edges of the bounding box become translucent and the label becomes illegible. In addition the sides of bounding box and the vertical and horizontal lines become very wide. This is probably due to them being set at a static pixel width regardless of image resolution. This was mentioned in issue #160 . 

image

-&nbsp;Image at 320 x 240

**Review by uvidyadharan — APPROVED** [review]

**Pull request merged**
